services:
  webserver:
    build: webclient
    ports:
      - 8080:80
    restart: unless-stopped
  rust_rest_api_server_sqrt:
    build: rust/exact-square-root-rest-api-server
    ports:
      - 8083:8083
    restart: unless-stopped
  haskell_rest_api_server_sqrt:
    build: haskell/exact-square-root-rest-api-server
    ports:
      - 8082:8082
    restart: unless-stopped
